site_name: htb-cli documentation
theme:
  name: material
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GoToolSharing/htb-cli
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - content.code.copy
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 


      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: codehilite
          class: codehilite
          format: !!python/name:pymdownx.superfences.fence_code_format
  - codehilite:
      guess_lang: false
      css_class: highlight
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite


nav:
    - Home: index.md
    - Installation: installation.md
    - Configuration: configuration.md
    - Commands:
      - Introduction: commands/introduction.md
      - Version: commands/version.md
      - Update: commands/update.md
      - Shoutbox: commands/shoutbox.md
      - Sherlocks: commands/sherlocks.md
      - Info: commands/info.md
      - Machines: commands/machines.md
      - Start: commands/start.md
      - Stop: commands/stop.md
      - Reset: commands/reset.md
      - Submit: commands/submit.md
      - VPN: commands/vpn.md
      - Status: commands/status.md
     
  